platform :ios, '9.0'
target ‘AI_XG’ do

pod 'JPush', '~> 3.0.6'
pod 'Bugly', '~> 2.5.0'
pod 'SDWebImage', '~> 4.0.0’
pod 'SDAutoLayout', '~> 2.2.0'
#pod 'IQKeyboardManager', '~> 5.0.3’
pod 'SDCycleScrollView', '~> 1.73'
pod 'MBProgressHUD', '~> 1.0.0’
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.14'
pod 'YTKNetwork', '~> 2.0.4'
pod 'FMDB', '~> 2.7.2'
pod 'Google-Mobile-Ads-SDK', '~> 7.38.0'
#pod 'AMapLocation-NO-IDFA'
pod 'AVOSCloud', '~> 11.0.0'

pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCShare/UI'
pod 'UMCAnalytics'
pod 'UMCShare/Social/WeChat'
pod 'UMCShare/Social/QQ'

end
